CREATE OR REPLACE VIEW vw_grupos_aluno AS SELECT
  GRUP.ID_GRUPO_ESTUDO,
  GRUP.NOME,
  GRUP.DATA_ENCONTRO,
  GRUP.LOCAL,
  GRUP.DESCRICAO,
  GRUP.ID_DISCIPLINA,
  DISC.NOME AS NOME_DISCIPLINA,
  ALUN.ID_ALUNO,
  ALUN.VERSION AS VERSION
FROM GRUPOS_ESTUDO GRUP
INNER JOIN PARTICIPACOES PART ON PART.ID_GRUPO_ESTUDO = GRUP.ID_GRUPO_ESTUDO
INNER JOIN ALUNOS ALUN ON ALUN.ID_ALUNO = PART.ID_ALUNO
INNER JOIN DISCIPLINAS DISC ON DISC.ID_DISCIPLINA = GRUP.ID_DISCIPLINA;
